#!/usr/bin/env python
import findrox; findrox.version(1, 9, 13)
import os, rox, sys

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

import gtk, musicbox, xsoap

#see if another instance is running and pass it our args
window = xsoap.get_server("_ROX_MUSICBOX")
if window:
	xsoap.send_message(window, "load_songs", sys.argv[1:])
else:
	#if not then start a new instance
	try:
		gtk.threads_init()
		gtk.threads_enter()
		box = musicbox.MusicBox()
		box.show()
		rox.mainloop()
		gtk.threads_leave()
	except:
		rox.report_exception()


