#!/usr/bin/env python
import findrox
import rox
from rox import g
import musicbox

try:
	import rox.basedir
except ImportError:
	rox.croak('Need ROX-Lib 1.9.7 or later:\n'
		'http://rox.sourceforge.net/rox_lib.html')

g.threads_init()

box = musicbox.MusicBox()
box.show()

rox.mainloop()
