#!/usr/bin/env python
import findrox; findrox.version(1, 9, 13)
import rox
from rox import g

mbox_window = None
window = g.gdk.get_default_root_window()

xid = window.property_get(g.gdk.atom_intern("_ROX_MUSICBOX", False))
if xid:
	xid = xid[2][0]
	mbox_window = g.gdk.window_foreign_new(long(xid))

if mbox_window:
	atom_args = [g.gdk.atom_intern("next", False)]
	mbox_window.property_change(g.gdk.atom_intern("_XSOAP", False),
				"ATOM", 32, g.gdk.PROP_MODE_REPLACE, atom_args)
	g.gdk.flush()
else:
	rox.croak('You are not running MusicBox!')


